# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bPo3X0lrg1G+SLE0wLt/3SzjVWATAbPI4cKt4RznHdqg6m2/rbH6B3EJ5cXu/J/br3eqZlezdP+058vip0+cmD17mGczjOihDjbn1nkOvYe1MrSMjyB03aKI1OWvs/MpyzInv7W0hlidTO9RDjOwGObRvis28bbv1TRcwcxmEmUbXc56uSMaQEBOJhvs5VRopqWwVD4b79rqVxfR1oA6njk77/e/Cz3PQWT+RH+Fy2yw8Jcx890k4a9Q7BXmC5Xs+tHj3EVa++3sjgCWuqAPIob08C72btcISkFrPRVgYBZ7/nLEEPcIxcyvP2edYFjTLsAx4WQmxguNKkGH9/IloK4958uPE5tijKfOB3W3y+h4LBbDwDg1JVCwjqPgDX5FmIz6GyIZ2vDXSt0dWTqMSkni6yMzSvx3hFj7QAKXA9bnK/GCTUYFznyrGtkWXuVqvUqFRKri4QiT0w4dJtaqedJ3h7jYvk5zPJ3iQEgj0ZdMVIv/gVZMYrC5DMJuHQ+Fb0DuXrF9joSGwh6pqMjmNDp8k7BF/zyHf9Y6BfO0elgxgfk5lJVV+GhpECly69bBc+Y+TYjdEGzZ6kX8fLZmdTzQfjwHIn3ES5uSCMhQoX9jov+WdO1pCWxy3wga1KmpsyFApAdESYpTQ8yx4+PmxcsQh9PUwRH/7lLfp1kTK9Q="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
